vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        plants_image:
            uri_prefix: /images/plants
            upload_destination: '%kernel.project_dir%/public/images/plants'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
